// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content_box': string;
  'forget': string;
  'left': string;
  'login_box': string;
  'remember': string;
  'right': string;
}
export const cssExports: CssExports;
export default cssExports;
