// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'layout_box': string;
  'layout_breadcrumb': string;
  'layout_content': string;
  'layout_left': string;
  'layout_left_menu': string;
  'layout_main_box': string;
  'layout_right': string;
  'logout': string;
}
export const cssExports: CssExports;
export default cssExports;
